SELECT 'ORACLE', LPAD('ORACLE',10,'#'), RPAD('ORACLE',10,'#')
FROM DUAL;

SELECT RPAD('930521-',14,'*'), RPAD('010-9903-',13,'#')
FROM DUAL;

SELECT CONCAT(EMPNO,ENAME), CONCAT(EMPNO, CONCAT(' : ', ENAME))
FROM EMP;

SELECT EMPNO || ENAME, EMPNO ||' : '|| ENAME
FROM EMP;


SELECT ' ABC ', TRIM(' ABC ')
FROM DUAL;

SELECT ROUND('1234.5678',2)
FROM DUAL;

SELECT SYSDATE, ADD_MONTHS(SYSDATE,3)
FROM DUAL;

SELECT EMPNO,ENAME,HIREDATE, ADD_MONTHS(HIREDATE,60) AS WORK5YEARS
FROM EMP;

SELECT EMPNO,ENAME,HIREDATE,SYSDATE
FROM EMP
WHERE ADD_MONTHS(HIREDATE,120) < SYSDATE;

SELECT SYSDATE, ADD_MONTHS(SYSDATE,6)
FROM DUAL;

SELECT EMPNO, ENAME, HIREDATE, TRUNC(MONTHS_BETWEEN(SYSDATE,HIREDATE)) AS 일한개월수
FROM EMP;

SELECT TO_CHAR(SYSDATE, 'YY-MM-DD')
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'AM HH:MI:SS')
FROM DUAL;

SELECT TO_CHAR(SAL,'999,999'), TO_CHAR(SAL,'$999,999')
FROM EMP;

SELECT TO_DATE('19930521','YY-MM-DD')
FROM DUAL;

SELECT*
FROM EMP
WHERE HIREDATE > TO_DATE('1981.06.01','YY.MM.DD');


SELECT COMM, NVL(COMM,0)
FROM EMP;


SELECT EMPNO, ENAME, JOB, SAL,
        DECODE(JOB,
                'MANAGER', SAL*1.1,
                'SALESMAN', SAL*1.05,
                'ANALYST', SAL,
                SAL*1.03) AS UPSAL
FROM EMP;

SELECT EMPNO, ENAME, JOB, SAL,
        CASE JOB
            WHEN 'MANAGER' THEN SAL*1.1
            WHEN 'SALESMAN' THEN SAL*1.05
            WHEN 'ANALYST' THEN SAL
            ELSE SAL*1.03
        END AS UPSAL
FROM EMP;
                

--Q1

SELECT EMPNO, CONCAT(SUBSTR(EMPNO,1,2),'**') AS MASKING_EMPNO,
        ENAME,CONCAT(SUBSTR(ENAME,1,1),'****') AS MASKING_ENAME
FROM EMP
WHERE LENGTH(ENAME) >=5
AND LENGTH(ENAME)<6;

--Q2

SELECT EMPNO, ENAME, SAL,
        TRUNC(SAL/21.5,2) AS DAY_PAY,
        ROUND(SAL/21.5/8,1) AS TIME_PAY
FROM EMP;

--Q3

SELECT EMPNO, ENAME, HIREDATE,
        NEXT_DAY(ADD_MONTHS(HIREDATE,3),'월요일') AS R_JOB, NVL2(COMM, TO_CHAR(COMM),'N/A') AS COMM
FROM EMP;


--Q4

SELECT EMPNO,ENAME,MGR,
        CASE
            WHEN MGR IS NULL THEN '0000'
            WHEN MGR LIKE '75%' THEN '5555'
            WHEN SUBSTR(MGR,1,2) = '76' THEN '6666'
            WHEN MGR LIKE '77%' THEN '7777'
            WHEN MGR LIKE '88%' THEN '8888'
            ELSE TO_CHAR(MGR)
        END AS CHG_MGR
FROM EMP;







