SELECT DEPTNO, ROUND(AVG(SAL)) AS AVG_SAL,MAX(SAL),MIN(SAL),COUNT(*) AS CNT
FROM EMP
GROUP BY DEPTNO;

SELECT JOB, COUNT(JOB)
FROM EMP
GROUP BY JOB
HAVING COUNT(JOB) >= 3;

SELECT TO_CHAR(HIREDATE,'YYYY') AS HIRE_YEAR, DEPTNO, COUNT(*)
FROM EMP
GROUP BY TO_CHAR(HIREDATE,'YYYY'), DEPTNO;

SELECT NVL2(COMM,'O','X') AS EXIST_COMM , COUNT(*) AS CNT
FROM EMP
GROUP BY NVL2(COMM,'O','X');

SELECT DEPTNO,TO_CHAR(HIREDATE,'YYYY') AS HIRE_YEAR, COUNT(*), MAX(SAL), SUM(SAL), ROUND(AVG(SAL))
FROM EMP
GROUP BY CUBE(DEPTNO, TO_CHAR(HIREDATE,'YYYY'))
ORDER BY DEPTNO, HIRE_YEAR;

SELECT *
FROM EMP E
    JOIN SALGRADE S
    ON E.SAL BETWEEN S.LOSAL AND S.HISAL;
    
SELECT *
FROM EMP E
    JOIN EMP M
    ON E.EMPNO = M.MGR;
    
    
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL
FROM EMP E
    JOIN DEPT D
    ON E.DEPTNO = D.DEPTNO
WHERE SAL >2000;

SELECT D.DEPTNO, D.DNAME, ROUND(AVG(E.SAL)), MAX(E.SAL), MIN(E.SAL), COUNT(*)
FROM EMP E
    JOIN DEPT D
    ON E.DEPTNO = D.DEPTNO
GROUP BY D.DEPTNO, D.DNAME;

SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.JOB, E.SAL
FROM EMP E
  JOIN DEPT D
  ON E.DEPTNO = D.DEPTNO
ORDER BY D.DEPTNO,E.ENAME;

SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, M.EMPNO, E.SAL,
        E.DEPTNO, S.LOSAL, S.HISAL, S.GRADE, M.EMPNO, M.ENAME
FROM EMP E
    RIGHT OUTER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
    JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
    LEFT OUTER JOIN EMP M ON E.MGR = M.EMPNO
ORDER BY D.DEPTNO, E.EMPNO;
    


















