--Q1
CREATE TABLE CHAP10HW_EMP AS SELECT * FROM EMP;
CREATE TABLE CHAP10HW_DEPT AS SELECT * FROM DEPT;
CREATE TABLE CHAP10HW_SALGRADE AS SELECT * FROM SALGRADE;

INSERT INTO CHAP10HW_DEPT(DEPTNO,DNAME,LOC)
VALUES (50, 'ORACLE', 'BUSAN');

INSERT INTO CHAP10HW_DEPT(DEPTNO,DNAME,LOC)
VALUES (60,'SQL','ILSAN');

INSERT INTO CHAP10HW_DEPT(DEPTNO,DNAME,LOC)
VALUES (70,'SELECT','INCHEON');

INSERT INTO CHAP10HW_DEPT(DEPTNO,DNAME,LOC)
VALUES (80,'DML','BUNDANG');

SELECT*
FROM CHAP10HW_DEPT;

--Q2

INSERT INTO CHAP10HW_EMP(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES (7201,'TEST_USER1','MANAGER',7788,'2016-01-02',4500,NULL,50);

SELECT *
FROM CHAP10HW_EMP;

UPDATE CHAP10HW_EMP
SET DEPTNO = 70
WHERE SAL > (SELECT AVG(SAL)
                FROM CHAP10HW_EMP
                WHERE DEPTNO = 50);
                
--Q4
UPDATE CHAP10HW_EMP
SET SAL = SAL*1.1, DEPTNO = 80
WHERE HIREDATE > (SELECT MIN(HIREDATE)
                    FROM CHAP10HW_EMP
                    WHERE DEPTNO = 30);

DELETE FROM CHAP10HW_EMP
WHERE ENAME IN (SELECT ENAME
                FROM CHAP10HW_EMP E
                    JOIN CHAP10HW_SALGRADE S
                    ON E.SAL BETWEEN S.LOSAL AND S.HISAL
                WHERE S.GRADE = 5);
                
DROP TABLE CHAP10HW_SALGRADE;
