CREATE TABLE TABLE_NOTNULL(
    LOGIN_ID VARCHAR2(20) NOT NULL,
    LOGIN_PWD VARCHAR2(20) NOT NULL,
    TEL     VARCHAR2(20)
    );
    
SELECT*
FROM ALL_CONSTRAINTS
WHERE TABLE_NAME = 'TABLE_NOTNULL';

CREATE TABLE TABLE_NOTNULL2(
    LOGIN_ID VARCHAR2(20) CONSTRAINT TBLNN2_LGNID_NN NOT NULL,
    LOGIN_PW VARCHAR2(20) CONSTRAINT TBLNN2_LGNPW_NN NOT NULL,
    TEL     VARCHAR2(20)
    );
    
SELECT *
FROM ALL_CONSTRAINTS
WHERE TABLE_NAME = 'TABLE_NOTNULL2';

ALTER TABLE TABLE_NOTNULL2
MODIFY (TEL NOT NULL);

INSERT INTO TABLE_NOTNULL(LOGIN_ID,LOGIN_PWD,TEL)
VALUES ('TEST_ID_01','1234',NULL);

SELECT*FROM TABLE_NOTNULL2;

ALTER TABLE TABLE_NOTNULL
MODIFY (TEL NOT NULL);

UPDATE TABLE_NOTNULL
SET TEL = '010-1234-5678'
WHERE LOGIN_ID = 'TEST_ID_01';

ALTER TABLE TABLE_NOTNULL2
MODIFY ( TEL CONSTRAINT TBLNN_TEL_NN NOT NULL);

ALTER TABLE TABLE_NOTNULL2
RENAME CONSTRAINT SYS_C007144 TO TBLNN2_TEL_NN;

ALTER TABLE TABLE_NOTNULL2
DROP CONSTRAINT TBLNN2_TEL_NN;

----------------------------------

CREATE TABLE TABLE_UNIQUE(
    LOGIN_ID VARCHAR2(20) UNIQUE,
    LOGIN_PW VARCHAR2(20) NOT NULL,
    TEL     VARCHAR2(20)
    );
    
    
SELECT*
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'TABLE_UNIQUE';

INSERT INTO TABLE_UNIQUE(LOGIN_ID,LOGIN_PW,TEL)
VALUES (NULL,'PW01','010-1234-5678');

SELECT*FROM TABLE_UNIQUE;

UPDATE TABLE_UNIQUE
SET LOGIN_ID = 'TEST_ID_01'
WHERE LOGIN_ID IS NULL;

CREATE TABLE TABLE_UNIQUE2(
    LOGIN_ID    VARCHAR2(20) CONSTRAINT TBLUNQ2_LGNID_UNQ UNIQUE,
    LOGIN_PW    VARCHAR2(20) CONSTRAINT TBLUNQ2_LGNPW_NN NOT NULL,
    TEL         VARCHAR2(20)
    );

SELECT*
FROM USER_CONSTRAINTS
WHERE TABLE_NAME LIKE 'TABLE_UNIQUE%';

ALTER TABLE TABLE_UNIQUE
MODIFY ( TEL UNIQUE);

UPDATE TABLE_UNIQUE
SET TEL = NULL;

ALTER TABLE TABLE_UNIQUE2
MODIFY (TEL CONSTRAINT TBLUNQ2_TEL_UNQ UNIQUE);

ALTER TABLE TABLE_UNIQUE2
RENAME CONSTRAINT TBLUNQ2_TEL_UNQ TO UNQ2;

ALTER TABLE TABLE_UNIQUE2
DROP CONSTRAINT UNQ2;


--------------------------------
CREATE TABLE TABLE_PK(
    LOGIN_ID    VARCHAR2(20)    PRIMARY KEY,
    LOGIN_PW    VARCHAR2(20)    NOT NULL,
    TEL         VARCHAR2(20)
    );
    
SELECT*
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'TABLE_PK';

DESC TABLE_PK;

SELECT*
FROM USER_INDEXES
WHERE TABLE_NAME = 'TABLE_PK';

CREATE TABLE TABLE_PK2(
    LOGIN_ID    VARCHAR2(20),
    LOGIN_PW    VARCHAR2(20) NOT NULL,
    TEL         VARCHAR2(20),
    CONSTRAINT TBLPK2_LGNID_PK PRIMARY KEY(LOGIN_ID)
    );

SELECT*
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'TABLE_PK2';


----------------------------------------
CREATE TABLE DEPT_FK(
    DEPTNO NUMBER(2) CONSTRAINT DEPTKF_DEPTNO_PK PRIMARY KEY,
    DNAME   VARCHAR2(14),
    LOC     VARCHAR2(13)
    );

CREATE TABLE EMP_FK(
    EMPNO   NUMBER(4) CONSTRAINT EMPFK_EMPNO_PK PRIMARY KEY,
    ENAME   VARCHAR2(10),
    JOB     VARCHAR2(9),
    MGR     NUMBER(4),
    HIREDATE DATE,
    SAL     NUMBER(7,2),
    COMM    NUMBER(7,2),
    DEPTNO  NUMBER(2) CONSTRAINT EMPFK_DEPTNO_FK REFERENCES DEPT_FK(DEPTNO)
    );

INSERT INTO DEPT_FK(DEPTNO,DNAME,LOC)
VALUES(10,'TEST_DNAME','TEST_LOC');

INSERT INTO EMP_FK(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES(9999,'TEST_ENAME','TESTJOB',NULL,TO_DATE(SYSDATE,'YYYY/MM/DD'),3000,NULL,10);

SELECT*FROM EMP_FK;


CREATE TABLE TABLE_CHECK(
    LOGIN_ID    VARCHAR2(20)    CONSTRAINT TBLCK_LGNID_PK PRIMARY KEY,
    LOGIN_PW    VARCHAR2(20)    CONSTRAINT TBLCK_LGNID_CK CHECK(LENGTH(LOGIN_PW)>3),
    TEL         VARCHAR2(20)
    );

INSERT INTO TABLE_CHECK(LOGIN_ID,LOGIN_PW,TEL)
VALUES ('TEST_ID','1234','010-1234-5678');

SELECT*
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'TABLE_CHECK';

-------------------------------------


CREATE TABLE DEPT_CONST(
    DEPTNO  NUMBER(2)   CONSTRAINT DEPTCONST_DEPTNO_PK PRIMARY KEY,
    DNAME   VARCHAR2(14) CONSTRAINT DEPTCONST_DNAME_UNQ UNIQUE,
    LOC     VARCHAR2(13) CONSTRAINT DEPTCONST_LOC_NN    NOT NULL
    );
    
CREATE TABLE EMP_CONST(
    EMPNO   NUMBER(4)   CONSTRAINT EMPCONST_EMPNO_PK PRIMARY KEY,
    ENAME   VARCHAR2(10) CONSTRAINT EMPCONST_ENAME_NN NOT NULL,
    JOB     VARCHAR2(9),
    TEL     VARCHAR2(20) CONSTRAINT EMPCONST_TEL_UNQ UNIQUE,
    HIREDATE DATE,
    SAL     NUMBER(7,2) CONSTRAINT EMPCONST_SAL_CK CHECK(SAL>=1000 AND SAL<=9999),
    COMM    NUMBER(7,2),
    DEPTNO  NUMBER(2) CONSTRAINT EMPCONST_DEPTNO_FK REFERENCES DEPT_CONST(DEPTNO)
    );

SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN('DEPT_CONST','EMP_CONST');











































