CREATE TABLE TABLE_NOTNULL(
    LOGIN_ID VARCHAR2(20) NOT NULL,
    LOGIN_PWD VARCHAR2(20) NOT NULL,
    TEL     VARCHAR2(20)
    );
    
SELECT*
FROM ALL_CONSTRAINTS
WHERE TABLE_NAME = 'TABLE_NOTNULL';
