CREATE TABLE TABLE_NOTNULL(
    LOGIN_ID VARCHAR2(20) NOT NULL,
    LOGIN_PWD VARCHAR2(20) NOT NULL,
    TEL     VARCHAR2(20)
    );
    
SELECT*
FROM ALL_CONSTRAINTS
WHERE TABLE_NAME = 'TABLE_NOTNULL';

CREATE TABLE TABLE_NOTNULL2(
    LOGIN_ID VARCHAR2(20) CONSTRAINT TBLNN2_LGNID_NN NOT NULL,
    LOGIN_PW VARCHAR2(20) CONSTRAINT TBLNN2_LGNPW_NN NOT NULL,
    TEL     VARCHAR2(20)
    );
    
SELECT *
FROM ALL_CONSTRAINTS
WHERE TABLE_NAME = 'TABLE_NOTNULL2';

ALTER TABLE TABLE_NOTNULL2
MODIFY (TEL NOT NULL);

INSERT INTO TABLE_NOTNULL(LOGIN_ID,LOGIN_PWD,TEL)
VALUES ('TEST_ID_01','1234',NULL);

SELECT*FROM TABLE_NOTNULL2;

ALTER TABLE TABLE_NOTNULL
MODIFY (TEL NOT NULL);

UPDATE TABLE_NOTNULL
SET TEL = '010-1234-5678'
WHERE LOGIN_ID = 'TEST_ID_01';

ALTER TABLE TABLE_NOTNULL2
MODIFY ( TEL CONSTRAINT TBLNN_TEL_NN NOT NULL);

ALTER TABLE TABLE_NOTNULL2
RENAME CONSTRAINT SYS_C007144 TO TBLNN2_TEL_NN;

ALTER TABLE TABLE_NOTNULL2
DROP CONSTRAINT TBLNN2_TEL_NN;

----------------------------------

CREATE TABLE TABLE_UNIQUE(
    LOGIN_ID VARCHAR2(20) UNIQUE,
    LOGIN_PW VARCHAR2(20) NOT NULL,
    TEL     VARCHAR2(20)
    );
    
    
SELECT*
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'TABLE_UNIQUE';

INSERT INTO TABLE_UNIQUE(LOGIN_ID,LOGIN_PW,TEL)
VALUES (NULL,'PW01','010-1234-5678');

SELECT*FROM TABLE_UNIQUE;

UPDATE TABLE_UNIQUE
SET LOGIN_ID = 'TEST_ID_01'
WHERE LOGIN_ID IS NULL;

CREATE TABLE TABLE_UNIQUE2(
    LOGIN_ID    VARCHAR2(20) CONSTRAINT TBLUNQ2_LGNID_UNQ UNIQUE,
    LOGIN_PW    VARCHAR2(20) CONSTRAINT TBLUNQ2_LGNPW_NN NOT NULL,
    TEL         VARCHAR2(20)
    );

SELECT*
FROM USER_CONSTRAINTS
WHERE TABLE_NAME LIKE 'TABLE_UNIQUE%';

ALTER TABLE TABLE_UNIQUE
MODIFY ( TEL UNIQUE);

UPDATE TABLE_UNIQUE
SET TEL = NULL;

ALTER TABLE TABLE_UNIQUE2
MODIFY (TEL CONSTRAINT TBLUNQ2_TEL_UNQ UNIQUE);

ALTER TABLE TABLE_UNIQUE2
RENAME CONSTRAINT TBLUNQ2_TEL_UNQ TO UNQ2;

ALTER TABLE TABLE_UNIQUE2
DROP CONSTRAINT UNQ2;


--------------------------------
CREATE TABLE TABLE_PK(
    LOGIN_ID    VARCHAR2(20)    PRIMARY KEY,
    LOGIN_PW    VARCHAR2(20)    NOT NULL,
    TEL         VARCHAR2(20)
    );
    
SELECT*
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'TABLE_PK';

DESC TABLE_PK;

SELECT*
FROM USER_INDEXES
WHERE TABLE_NAME = 'TABLE_PK';

CREATE TABLE TABLE_PK2(
    LOGIN_ID    VARCHAR2(20),
    LOGIN_PW    VARCHAR2(20) NOT NULL,
    TEL         VARCHAR2(20),
    CONSTRAINT TBLPK2_LGNID_PK PRIMARY KEY(LOGIN_ID)
    );

SELECT*
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'TABLE_PK2';
























