SELECT *
FROM EMP
WHERE DEPTNO IN(10,20);

SELECT ENAME, SUBSTR(ENAME,1,3)
FROM EMP;

SELECT INSTR('HELLO, ORACLE!','Z')
FROM DUAL;

SELECT ENAME || ' : ' || EMPNO
FROM EMP;

-- Q1
SELECT EMPNO, SUBSTR(EMPNO,1,2)||'**' AS MASKING_EMPNO,
        ENAME, SUBSTR(ENAME,1,1)||'****' AS MASKING_ENAME
FROM EMP
WHERE LENGTH(ENAME) >=5
AND LENGTH(ENAME) <6;

-- Q2
SELECT EMPNO,ENAME,SAL,
        TRUNC(SAL/21.5,2)AS DAY_PAY,
        ROUND(SAL/(21.5*8),1) AS TIME_PAY
FROM EMP;

-- Q3
SELECT EMPNO, ENAME, HIREDATE,
        TO_CHAR(ADD_MONTHS(HIREDATE, 3), 'YYYY-MM-DD') AS R_JOB,
        NVL2(COMM, TO_CHAR(COMM), 'N/A') AS COMM
FROM EMP;

-- Q4
SELECT EMPNO, ENAME, NVL2(MGR,TO_CHAR(MGR),' ') AS MGR,
        CASE
            WHEN MGR LIKE '75%' THEN '5555'
            WHEN MGR LIKE '76%' THEN '6666'
            WHEN MGR LIKE '77%' THEN '7777'
            WHEN MGR LIKE '78%' THEN '8888'
            ELSE                '0000'
        END AS CHG_MGR
            
FROM EMP;


--Q1
SELECT DEPTNO, TRUNC(AVG(SAL)),MAX(SAL),MIN(SAL),COUNT(*)
FROM EMP
GROUP BY DEPTNO;

--Q2
SELECT JOB, COUNT(*)
FROM EMP
GROUP BY JOB
HAVING COUNT(*) >=3;

--Q3
SELECT TO_CHAR(HIREDATE,'YYYY') AS HIRE_YEAR,
        DEPTNO,COUNT(*) AS CNT
FROM EMP
GROUP BY TO_CHAR(HIREDATE,'YYYY'),DEPTNO;


--Q4
SELECT NVL2(COMM,'O','x') AS EXIST_COMM,
        COUNT(*) AS CNT
FROM EMP
GROUP BY NVL2(COMM,'O','x');

--Q5
SELECT DEPTNO,
        TO_CHAR(HIREDATE,'YYYY') AS HIRE_YEAR,
        COUNT(*) AS CNT,
        MAX(SAL),
        SUM(SAL),
        AVG(SAL)
FROM EMP
GROUP BY ROLLUP(DEPTNO,TO_CHAR(HIREDATE,'YYYY'));


--Q1
SELECT E.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL
FROM EMP E,DEPT D
WHERE E.DEPTNO = D.DEPTNO
AND E.SAL >2000;

SELECT E.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL
FROM EMP E
    JOIN DEPT D
    ON E.DEPTNO = D.DEPTNO
WHERE E.SAL > 2000;

--Q2
SELECT E.DEPTNO, TRUNC(AVG(E.SAL)), MAX(E.SAL), MIN(E.SAL), COUNT(*)
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
GROUP BY D.DEPTNO
ORDER BY E.DEPTNO;

SELECT E.DEPTNO, TRUNC(AVG(E.SAL)), MAX(E.SAL), MIN(E.SAL), COUNT(*)
FROM EMP E
    JOIN DEPT D
    ON E.DEPTNO = D.DEPTNO
GROUP BY D.DEPTNO
ORDER BY E.DEPTNO;

--Q3
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.JOB, E.SAL
FROM EMP E, DEPT D
WHERE E.DEPTNO(+) = D.DEPTNO;

SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.JOB, E.SAL
FROM EMP E
    RIGHT OUTER JOIN DEPT D
    ON E.DEPTNO = D.DEPTNO;
    
--Q4
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.MGR,E.SAL,
        E.DEPTNO, S.LOSAL, S.HISAL, S.GRADE,
        M.EMPNO, M.ENAME
FROM EMP E
    RIGHT OUTER JOIN DEPT D
        ON E.DEPTNO = D.DEPTNO
    LEFT OUTER JOIN EMP M
        ON E.MGR = M.EMPNO
    LEFT OUTER JOIN SALGRADE S
        ON E.SAL BETWEEN S.LOSAL AND S. HISAL
ORDER BY D.DEPTNO, E.EMPNO;



--서브쿼리
--p9-1
SELECT *
FROM EMP
WHERE SAL > (SELECT SAL
            FROM EMP
            WHERE ENAME = 'JONES');
            
--P9-7
SELECT *
FROM EMP
WHERE SAL IN (SELECT MAX(SAL)
                FROM EMP
                GROUP BY DEPTNO);


--Q1
SELECT E.JOB, E.EMPNO, E.ENAME, E.SAL, D.DEPTNO, D.DNAME
FROM EMP E
    JOIN DEPT D
    ON E.DEPTNO = D.DEPTNO
WHERE E.JOB = (SELECT JOB
                FROM EMP
                WHERE ENAME = 'ALLEN');

--Q2
SELECT E.EMPNO, E.ENAME, D.DNAME, TO_CHAR(E.HIREDATE,'YYYY-MM-DD') AS HIREDATE, D.LOC, E.SAL, S.GRADE
FROM EMP E
    JOIN DEPT D
        ON E.DEPTNO = D.DEPTNO
    JOIN SALGRADE S
        ON E.SAL BETWEEN S.LOSAL AND S.HISAL
WHERE SAL > (SELECT AVG(SAL)
            FROM EMP)
ORDER BY E.SAL DESC, E.EMPNO;

--Q3
SELECT E.EMPNO, E.ENAME, E.JOB, D.DEPTNO, D.DNAME, D.LOC
FROM EMP E
    JOIN DEPT D
    ON E.DEPTNO = D.DEPTNO
WHERE E.JOB != ALL (SELECT JOB
                    FROM EMP
                    WHERE DEPTNO = 30)
AND D.DEPTNO = 10;

--Q4
SELECT E.EMPNO, E.ENAME, E.SAL, S.GRADE
FROM EMP E
    JOIN SALGRADE S
    ON E.SAL BETWEEN S.LOSAL AND S.HISAL
WHERE E.SAL > ALL (SELECT SAL
                    FROM EMP
                    WHERE JOB = 'SALESMAN')
ORDER BY E.EMPNO;

SELECT E.EMPNO, E.ENAME, E.SAL, S.GRADE
FROM EMP E
    JOIN SALGRADE S
    ON E.SAL BETWEEN S.LOSAL AND S.HISAL
WHERE E.SAL > (SELECT MAX(SAL)
               FROM EMP
               WHERE JOB = 'SALESMAN')
ORDER BY E.EMPNO;

-----------------------------
--------DML--------------------
--------------------------------

CREATE TABLE DEPT_TEMP
AS SELECT*FROM DEPT;

INSERT INTO DEPT_TEMP(DEPTNO, DNAME, LOC)
VALUES(50,'DATABASE','SEOUL');

SELECT*
FROM DEPT_TEMP;

CREATE TABLE EMP_TEMP
AS
SELECT*
FROM EMP
WHERE 1<>1;

SELECT*
FROM EMP_TEMP;

INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES(9999, '홍길동','PRESIDENT',NULL,'2001.01.01',5000,1000,10);

INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES(2111, '이순신','MANAGER',9999,TO_DATE('07/03/20','YY/MM/DD'),4000,NULL,20);


-------------------------
---------DML --- UPDATE----------
-------------------------

CREATE TABLE DEPT_TEMP2
AS SELECT*FROM DEPT;

UPDATE DEPT_TEMP2
SET LOC ='SEOUL';

SELECT * FROM DEPT_TEMP2;

ROLLBACK;

UPDATE DEPT_TEMP2
SET DNAME = 'DATABASE',
    LOC = 'SEOUL'
WHERE DEPTNO = 40;

UPDATE DEPT_TEMP2
SET (DNAME, LOC) = (SELECT DNAME, LOC
                 FROM DEPT
                 WHERE DEPTNO = 40)
WHERE DEPTNO=40;

----------------------------
--------DELETE---------------
-----------------------------

CREATE TABLE EMP_TEMP2
AS SELECT* FROM EMP;

DELETE FROM EMP_TEMP2
WHERE JOB = 'MANAGER';

SELECT * FROM EMP_TEMP2;

ROLLBACK;

--P10-24
DELETE FROM EMP_TEMP2
WHERE EMPNO IN (SELECT E.EMPNO
                FROM EMP_TEMP2 E
                    JOIN SALGRADE S
                    ON E.SAL BETWEEN S.LOSAL AND S.HISAL
                WHERE S.GRADE = 3
                AND E.DEPTNO = 30);

SELECT*FROM EMP_TEMP2;
























