CREATE TABLE MEMBER_DDL (
    ID      VARCHAR2(50) CONSTRAINT MBDDL_ID_PK PRIMARY KEY,
    PASSWD  VARCHAR2(60),
    NAME    VARCHAR2(50),
    AGE     NUMBER(11),
    GENDER  VARCHAR2(5),
    EMAIL   VARCHAR2(30),
    REG_DATE DATE,
    ADDRESS VARCHAR2(100),
    TEEL    VARCHAR2(20)
    );

DESC MEMBER_DDL;

INSERT INTO MEMBER_DDL(ID,PASSWD,NAME,AGE,GENDER,EMAIL,REG_DATE,ADDRESS,TEEL)
VALUES('aaa','1234','홍길동',29,'남','aaa@a.com',sysdate,'부산시 부산진구','010-1111-1111');

SELECT* FROM MEMBER_DDL;


INSERT INTO MEMBER_DDL(ID,PASSWD,NAME)
VALUES('bbb','1234','성춘향');

SELECT* FROM MEMBER_DDL;

SELECT ID, NAME, GENDER
FROM MEMBER_DDL
WHERE GENDER = '남';

UPDATE MEMBER_DDL
SET AGE = 27, GENDER = '여', ADDRESS = '부산시 해운대구'
WHERE ID = 'bbb';

SELECT* FROM MEMBER_DDL;

DELETE MEMBER_DDL
WHERE ID = 'bbb';

SELECT* FROM MEMBER_DDL;
